Just muted lines

diff --git a/.github/workflows/handlepullrequestfeature.yml b/.github/workflows/handlepullrequestfeature.yml
--- a/.github/workflows/handlepullrequestfeature.yml
+++ b/.github/workflows/handlepullrequestfeature.yml
@@ -49,10 +49,10 @@ jobs:
               run: |
                   echo "${{ secrets.DEVHUB_SFDX_URL}}" > ./DEVHUB_SFDX_URL.txt
                   secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
-                  if [ $secretFileSize == 1 ]; then
-                      echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
-                      exit 1;
-                  fi
+                 # if [ $secretFileSize == 1 ]; then
+                  #    echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
+                   #   exit 1;
+                 # fi
                   
           # Authenticate dev hub
             - name: 'Authenticate Dev Hub'
