Update handlepullrequestfeature.yml

diff --git a/.github/workflows/handlepullrequestfeature.yml b/.github/workflows/handlepullrequestfeature.yml
--- a/.github/workflows/handlepullrequestfeature.yml
+++ b/.github/workflows/handlepullrequestfeature.yml
@@ -48,11 +48,11 @@ jobs:
               shell: bash
               run: |
                   echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt
-                 # secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
-                 # if [ $secretFileSize == 1 ]; then
-                  #    echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
-                   #   exit 1;
-                 # fi
+                  secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
+                  if [ $secretFileSize == 1 ]; then
+                      echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
+                      exit 1;
+                  fi
                   
           # Authenticate dev hub
             - name: 'Authenticate Dev Hub'
