sda

diff --git a/.github/workflows/handlepullrequestfeature.yml b/.github/workflows/handlepullrequestfeature.yml
--- a/.github/workflows/handlepullrequestfeature.yml
+++ b/.github/workflows/handlepullrequestfeature.yml
@@ -47,7 +47,12 @@ jobs:
             - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
               shell: bash
               run: |
-                  echo "${{ secrets.DEVHUB_SFDX_URL}}" 
+                  echo "${{ secrets.DEVHUB_SFDX_URL}}" > ./DEVHUB_SFDX_URL.txt
+                  secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
+                  if [ $secretFileSize == 1 ]; then
+                      echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
+                      exit 1;
+                  fi
                   
           # Authenticate dev hub
             - name: 'Authenticate Dev Hub'
